FROM ubuntu:latest

# Instala dependências básicas e Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-locust iproute2 iputils-ping net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Configura o ping para usuários não-root e cria usuário
RUN chmod u+s /bin/ping && \
    useradd -m -s /bin/bash locust && \
    chown -R locust:locust /home/locust

# Copia o arquivo de testes
COPY --chown=locust:locust testing/locustfile.py /home/locust/locustfile.py

# Define diretório de trabalho
WORKDIR /home/locust

# Usuário não-root
USER locust

# Comando padrão
CMD ["locust"]