FROM ubuntu:latest

# Instala dependências básicas e Python
RUN apt-get update && \
    apt-get install -y python3 python3-pip python3-locust iproute2 iputils-ping net-tools && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/*

# Cria usuário e diretório para o Locust
RUN useradd -m -s /bin/bash locust && \
    chown -R locust:locust /home/locust

# Copia o arquivo de testes com permissões adequadas
COPY --chown=locust:locust testing/locustfile.py /home/locust/locustfile.py

# Define diretório de trabalho
WORKDIR /home/locust

# Usuário não-root
USER locust

# Comando padrão para executar o Locust
CMD ["locust"]